version: "3"
volumes:
  db:
services:
  # backend:
  #   build:
  #     context: .
  #   tty: true
  #   ports:
  #     - 4000:4000
  #   # ベンチマークのためにマウントする
  #   volumes:
  #     - ./isucon9-qualify/initial-data:/isucon9-qualify/initial-data
  #     - ./isucon9-qualify/webapp/public/static:/isucon9-qualify/webapp/public/static
  #     - ./isucon9-qualify/bin/benchmarker:/isucon9-qualify/bin/benchmarker
  #   entrypoint: dockerize -timeout 60s -wait tcp://db:3306
  #   command: ./piscon_portal
  #   environment:
  #     MARIADB_HOST: db
  #     MARIADB_USERNAME: isucon
  #     MARIADB_PASSWORD: isucon
  #     MARIADB_DATABASE: isucon
  #   depends_on:
  #     - db
  # frontend:
  #   build:
  #     context: ./client
  #   tty: true
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./client/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - backend
  db:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./db/init:/docker-entrypoint-initdb.d
      # 永続化
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
